### PR TITLE
SheetsRegistryProvide renamed to JssProvider in latest React-JSS

### PR DESCRIPTION
**Pull request by VolkRiot**
Renamed Component -- Same functionality;

https://github.com/cssinjs/react-jss/commit/f78165a9dca43a2115fbde956668c7136e86ae37

### CODE REVIEW

**Comment by VolkRiot** [comment]
Notice that is being handled...

**Comment by verekia** [comment]
Sorry man, there are a lot of things that need to be updated in the tutorial. I'll have to do another major update soon.

**Comment by artemkovalyov** [comment]
Thank you, Volk, just today was suffering from this issue.

**Comment by VolkRiot** [comment]
@verekia No, worries man. Great tutorial. Did the whole thing! Learned a lot.

**Pull request closed without merging**
