### PR TITLE
Added an extra 0 for readable sortiing in Github web

### PR DESCRIPTION
**Pull request by nagamalli9999**
Now the sorting will not mess up the reading order in GitHub

### CODE REVIEW

**Comment by nagamalli9999** [comment]
I want to help, can you explain what I can do with this PR. I think this is an issue with Git.

**Comment by verekia** [comment]
Hm, I think that will be tricky with a PR, due to all the changes I'm making. Would you mind if I make this change in master myself?

**Comment by nagamalli9999** [comment]
Yes, please go ahead

**Comment by verekia** [comment]
It's fixed in the v2 of the tutorial, which is still a WIP. I plan to release it this week or the next one. Closing this PR :)

**Pull request closed without merging**
