### PR TITLE
BG translation done.

### PR DESCRIPTION
**Pull request by mihailgaberov**

### CODE REVIEW

**Comment by verekia** [comment]
Hey! Great job my friend!

Your pull request to the English repository should just be a link on the main README pointing to your forked repo. Can you make a new PR?

Cheers!

**Comment by mihailgaberov** [comment]
Sure! I forgot it, sorry :)

**Comment by verekia** [comment]
I mean can you close this PR and create a new one *just* with the README change? Because right now your PR overrides the entire English repo ;)

**Comment by mihailgaberov** [comment]
Ah! Sorry! Just a sec.

**Pull request closed without merging**
